# /etc/keepalived/keepalived.conf — VM2 (BACKUP)
vrrp_instance VI_1 {
    state BACKUP
    interface enp0s8
    virtual_router_id 51
    priority 100
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass CAMBIAR_CLAVE_VRRP   # misma clave en ambos nodos
    }

    virtual_ipaddress {
        192.168.1.100
    }
}
